// zh-CN-map.mjs — German source string -> Simplified Chinese translation.
//
// Keys must match the <source> text of translations/fmplayeranalyzer_en.ts
// exactly (including the \n line breaks of multi-line messages and the
// %1/%2/%% placeholders, which must be preserved in the translation). Line
// breaks are always written as \n — never \r\n — because an XML parser
// normalises CRLF to LF before the text reaches the application, so a CR would
// end up inside the compiled message and never match the string the C++ code
// builds at runtime. The TS catalogue and the compiled .qm are generated by
// tools/build-ts.mjs and tools/build-qm.mjs.
//
// Vocabulary (keep consistent across the whole UI):
//   Verein=Verein俱乐部  Spieler=球员  Rolle=角色  Taktik=战术  Kader=阵容
//   Startelf=首发  Zweitteam=二队/Jugend=青年队  Verletzung/Persönlichkeit=性格
//   Marktwert=身价  Gehalt=周薪  Spielzeit=出场时间  Note=评分  Talent=天赋
//   Abgänge=转会离队  Nominierung=征召  Kader-Auswahl=阵容选择

export const ZH = {
    // ---------------------------------------------------------------- departures
    'Spieler-Abgänge klären': '处理球员离队',
    'Diese Spieler stehen in der Datenbank bei deinem Verein, waren aber nicht in der hochgeladenen Kader-Datei. Standardmäßig gelten alle als gegangen und werden zu Free Agents (FrA) — hake die aus, die geblieben sind, und trage bei den anderen bei Bedarf einen neuen Verein oder \'Retired\' ein.':
        '这些球员在数据库中属于你的俱乐部，但并未出现在上传的阵容文件中。默认情况下他们全部视为已离队并成为自由球员（FrA）——请取消勾选仍然留队的球员，并为其他球员填写新俱乐部或“Retired”（退役）。',
    'Alle als gegangen markieren': '全部标记为已离队',
    'Spieler': '球员',
    'Gegangen': '已离队',
    'Neuer Verein / Status': '新俱乐部 / 状态',
    'Neuer Verein eintippen oder Status wählen (FrA = Free Agent, Retired = Karriereende).':
        '输入新俱乐部，或选择状态（FrA = 自由球员，Retired = 退役）。',
    'Abgänge bestätigen': '确认离队',

    // ------------------------------------------------------------- global / nav
    'Start fehlgeschlagen:\n%1': '启动失败：\n%1',
    'Dashboard': '仪表盘',
    'Rollen zuweisen': '分配角色',
    'Rollen-Analyse': '角色分析',
    'Spieler-Profil': '球员档案',
    'Squad Matrix': '阵容矩阵',
    'Best XI': '最佳阵容',
    'Gap-Analyse': '短板分析',
    'Taktik-Explorer': '战术探索',
    'Trainingsplan': '训练计划',
    'Transfers': '转会',
    'Spieler-Vergleich': '球员对比',
    'Entwicklung': '发展曲线',
    'Spieler bearbeiten': '编辑球员',
    'National-Dashboard': '国家队仪表盘',
    'Kader-Auswahl': '阵容选择',
    'Nominierungs-Assistent': '征召助手',
    'Neue Rolle': '新建角色',
    'Neue Taktik': '新建战术',
    'Einstellungen': '设置',

    '⛔ Unbesetzt': '⛔ 空缺',
    '🕳️⚠️ Versteckt + Offensichtlich': '🕳️⚠️ 隐性 + 显性',
    '🕳️ Versteckt': '🕳️ 隐性',
    '⚠️ Offensichtlich': '⚠️ 显性',

    'Sturm': '锋线',
    'Offensives Mittelfeld': '进攻中场',
    'Mittelfeld': '中场',
    'Defensives Mittelfeld': '防守中场',
    'Abwehr': '后防',

    'DWRS-Bewertungen werden berechnet…': '正在计算 DWRS 评分…',
    'Frische': '数据新鲜度',
    'Retired (%1)': '已退役 (%1)',
    'veraltet (%1)': '已过时 (%1)',
    'vor %1': '%1 之前',
    'aktuell': '最新',

    'Datenordner %1 konnte nicht angelegt werden.': '无法创建数据文件夹 %1。',

    // ------------------------------------------------------------ assign roles
    'Alle Spieler': '全部球员',
    'Spieler ohne Rollen': '未分配角色的球员',
    'Nicht von meinem Verein': '非本俱乐部球员',
    'Ohne Rollen, nicht von meinem Verein': '无角色且非本俱乐部',
    'Nach Name suchen…': '按姓名搜索…',
    'Filter:': '筛选：',
    'Verein:': '俱乐部：',
    'Position:': '位置：',
    'Auto-Zuweisung (nur Spieler ohne Rollen)': '自动分配（仅未分配角色的球员）',
    '⚠️ Auto-Zuweisung (ALLE Spieler)': '⚠️ 自动分配（全部球员）',
    'Änderungen speichern': '保存修改',
    'Name': '姓名',
    'Alter': '年龄',
    'Position': '位置',
    'Verein': '俱乐部',
    'Zugewiesene Rollen': '已分配角色',
    'Spieler in der Tabelle auswählen, um Rollen zu bearbeiten.':
        '在表格中选择一名球员以编辑其角色。',
    'Alle': '全部',
    '%1 Spieler mit ungespeicherten Änderungen': '%1 名球员有未保存的修改',
    'Rollen': '角色',
    'Keine Änderungen zum Speichern.': '没有需要保存的修改。',
    'Rollen für %1 Spieler aktualisiert und DWRS neu berechnet.':
        '已更新 %1 名球员的角色，并重新计算了 DWRS。',
    'Auto-Zuweisung': '自动分配',
    'Wirklich die Rollen ALLER Spieler anhand ihrer Positionen neu setzen? Manuell angepasste Rollen gehen dabei verloren.':
        '确实要根据位置重新设置所有球员的角色吗？手动调整过的角色将会丢失。',
    'Keine Spieler zu aktualisieren.': '没有需要更新的球员。',
    '%1 Spielern Rollen zugewiesen und DWRS neu berechnet.':
        '已为 %1 名球员分配角色，并重新计算了 DWRS。',

    // ---------------------------------------------------------------- best XI
    'Der Rechner nutzt einen \'Schwächstes-Glied-zuerst\'-Algorithmus: Statt Position für Position den besten Spieler zu wählen, wird immer zuerst die Position besetzt, auf der der beste verfügbare Spieler die geringste Verbesserung bringt — das ergibt insgesamt ausgewogenere und stärkere Teams.':
        '该计算器采用“最弱一环优先”算法：不是逐个位置挑选最强的球员，而是优先填补“最佳可用球员带来的提升最小”的位置——这样整体阵容会更均衡、更强。',
    'Startelf': '首发阵容',
    'B-Team': 'B 队',
    'Weitere Kader-Tiefe': '更多阵容深度',
    'Erste Mannschaft': '一线队',
    'Zweitteam-XI': '二队最佳阵容',
    'Jugend-XI': '青年队最佳阵容',
    '✔️ Zum Verwalten dieser Spieler dient die Seite \'Transfers\'.':
        '✔️ 请使用“转会”页面管理这些球员。',
    'Vielversprechende Talente zum Verleihen (nach Talent-Score)':
        '值得外租的潜力新星（按天赋评分）',
    'Rolle': '角色',
    'DWRS': 'DWRS',
    'Eignung': '适配度',
    'Beste Rolle': '最佳角色',
    'Bester DWRS': '最佳 DWRS',
    'Talent': '天赋',
    'Ent': '决心',
    'Arb': '工作投入',
    'Transfer': '转会',
    'Leihe': '租借',
    'Überzählige Spieler für Verkauf / Freigabe': '可出售 / 解约的多余球员',
    'Jugend && Zweitteam': '青年队 && 二队',
    'Bitte wähle zuerst deinen Verein (Dashboard oder Einstellungen).':
        '请先选择你的俱乐部（仪表盘或设置）。',
    'Zweitteam-XI (aus Überschuss des Hauptvereins)': '二队最佳阵容（来自主队多余球员）',
    'Zweitteam-XI (%1)': '二队最佳阵容（%1）',
    'Keine weiteren Spieler als Tiefen-Optionen für diese Taktik geeignet.':
        '没有其他球员适合作为该战术的替补深度选项。',

    // --------------------------------------------------------------- dashboard
    '⬆️ Neue Spielerdaten importieren (FM-HTML-Export)':
        '⬆️ 导入新的球员数据（FM HTML 导出）',
    'Keine Datei ausgewählt…': '未选择文件…',
    'Durchsuchen…': '浏览…',
    'Importieren': '导入',
    'Datei ist ein kompletter Kader-Export meines Vereins (Abgänge erkennen)':
        '该文件是我俱乐部的完整阵容导出（识别离队球员）',
    'Aktivieren, wenn die Datei NUR Spieler deines Haupt- und Zweitteams enthält. Die App erkennt Spieler, die den Verein verlassen haben, und fragt nach.':
        '若文件中只包含你的一线队和二队球员，请勾选此项。程序会识别已经离队的球员并询问你如何处理。',
    'Neuen/unzugeordneten Spielern automatisch Rollen zuweisen':
        '为新增 / 未分配角色的球员自动分配角色',
    'Kader-Analyse': '阵容分析',
    'Mein Verein:': '我的俱乐部：',
    'Analyse-Taktik:': '分析战术：',
    'Spieler im Kern-Kader': '核心阵容球员',
    'Gesamtwert Kader': '阵容总身价',
    'Ø Spielerwert': '平均身价',
    'Ø Alter': '平均年龄',
    'Positionsstärke': '位置实力',
    'Persönlichkeit': '性格',
    'Spielzeit': '出场时间',
    'Ø-Note': '平均评分',
    'Marktwert': '身价',
    '🎯 Transferziele': '🎯 转会目标',
    'Mögliche Verstärkungen aus deiner Scouting-Datenbank, basierend auf den Rollen der gewählten Taktik.':
        '来自你的球探数据库的潜在引援，基于所选战术所需的角色。',
    'Max. Alter:': '最大年龄：',
    'Max. Marktwert:': '最大身价：',
    '%1 Jahre': '%1 岁',
    'Bitte importiere Spielerdaten und wähle oben deinen Verein, um die Kader-Analyse zu sehen.':
        '请先导入球员数据并在上方选择你的俱乐部，即可查看阵容分析。',
    'Für die Taktik \'%1\' konnte kein Kader gebildet werden — es gibt keine passenden Spieler in deinem Verein.':
        '无法为战术“%1”组建阵容——你的俱乐部中没有合适的球员。',
    'Spieler bei %1 (%2)': '%1 的球员（%2）',
    '✅ Dein Kader ist gut aufgestellt! Keine klaren Verstärkungen innerhalb der Filterkriterien gefunden.':
        '✅ 你的阵容配置良好！在筛选条件内没有发现明显的引援目标。',
    'Upgrade für <b>%1</b>': '<b>%1</b> 的升级人选',
    '🎯 <b>Bewertung:</b> %1 %% (dein Bester: %2 %%)<br/>💰 <b>Wert:</b> %3<br/>🎂 <b>Alter:</b> %4':
        '🎯 <b>评分：</b>%1 %% （你的最佳：%2 %%）<br/>💰 <b>身价：</b>%3<br/>🎂 <b>年龄：</b>%4',
    'Verein: %1<br/>Positionen: %2': '俱乐部：%1<br/>位置：%2',
    'FM-HTML-Export auswählen': '选择 FM HTML 导出文件',
    'HTML-Dateien (*.html *.htm);;Alle Dateien (*)': 'HTML 文件 (*.html *.htm);;所有文件 (*)',
    'Import fehlgeschlagen': '导入失败',
    '❌ Die Datei konnte nicht importiert werden.\n\n%1\n\nMögliche Ursachen: kein <table>-Element, keine \'UID\'-Spalte oder kein gültiger Football-Manager-HTML-Export.':
        '❌ 无法导入该文件。\n\n%1\n\n可能原因：没有 <table> 元素、没有“UID”列，或者不是有效的 Football Manager HTML 导出文件。',
    'Import abgeschlossen': '导入完成',
    'Abgänge': '离队球员',
    '%1 Spieler-Datensätze aktualisiert.': '已更新 %1 条球员数据。',

    // ----------------------------------------------------------- DWRS progress
    'DWRS-Entwicklung': 'DWRS 发展',
    'Analysiere Entwicklungs-Trends: Kader-Durchschnitt je Rolle, Spieler gegen Spieler in einer Rolle oder ein einzelner Spieler im Detail.':
        '分析发展趋势：按角色查看阵容平均值、同一角色下球员之间的对比，或单个球员的详细分析。',
    'Analyse-Modus:': '分析模式：',
    'Kader-Überblick (nach Rolle)': '阵容概览（按角色）',
    'Spieler vs. Spieler (in einer Rolle)': '球员对比（同一角色）',
    'Einzelner Spieler (Detailanalyse)': '单个球员（详细分析）',
    'Taktik:': '战术：',
    'Rollen für das Diagramm:': '图表显示的角色：',
    'Rolle:': '角色：',
    'Spieler zum Vergleichen ankreuzen:': '勾选要对比的球员：',
    'Spieler:': '球员：',
    'Alle Rollen': '全部角色',
    'Keine Spieler für deinen Verein gefunden. Bitte wähle deinen Verein.':
        '没有找到你俱乐部的球员。请先选择你的俱乐部。',
    'Durchschnittliche Kader-Entwicklung für Rollen in \'%1\'': '“%1”中各角色的阵容平均发展',
    'Entwicklung als %1': '作为 %1 的发展曲线',
    'Entwicklung von %1': '%1 的发展曲线',
    'Keine historischen Daten für die aktuelle Auswahl gefunden.':
        '当前选择没有可用的历史数据。',

    // ------------------------------------------------------------- edit player
    'Spieler meines Vereins': '本俱乐部球员',
    'Markierungen für fehlende Daten: 🎯 Primärrolle, 📄 Spielzeit, 📍 natürliche Positionen':
        '缺失数据标记：🎯 主要角色，📄 出场时间，📍 擅长位置',
    'Oder: alle Spieler durchsuchen': '或者：搜索全部球员',
    'Verwaltung': '管理',
    'Spielzeit (Agreed Playing Time):': '出场时间（约定出场时间）：',
    'Taktisches Profil': '战术档案',
    'Natürliche Positionen:': '擅长位置：',
    'Die Positionen, auf denen dieser Spieler am effektivsten ist (Bonus in der Kader-Berechnung).':
        '该球员表现最出色的位置（在阵容计算中会有加成）。',
    'Primärrolle:': '主要角色：',
    'Keine': '无',
    'Links': '左脚',
    'Rechts': '右脚',
    'Überschreibt den bevorzugten Fuß im Best-XI-Rechner bei symmetrischen Rollen.':
        '在对称角色中覆盖最佳阵容计算器使用的惯用脚。',
    'Bevorzugte Seite:': '偏好侧：',
    '— Spieler auswählen —': '— 选择球员 —',
    'Bearbeite: %1 (%2)': '正在编辑：%1（%2）',
    'Änderungen für %1 gespeichert.': '已保存 %1 的修改。',

    // ----------------------------------------------------------- first run
    '%1 — Ersteinrichtung': '%1 — 初始设置',
    'Willkommen! Wähle den Ordner, in dem der Analyzer seine Daten ablegt\n(Datenbanken, Einstellungen, Rollen-Definitionen, Backups).\nDu kannst den Ordner später in den Einstellungen ändern.':
        '欢迎！请选择 Analyzer 存放数据的文件夹\n（数据库、设置、角色定义、备份）。\n之后可以在设置中更改该文件夹。',
    'Datenordner wählen': '选择数据文件夹',
    'Loslegen': '开始使用',
    'Beenden': '退出',

    // -------------------------------------------------------- gap analysis
    'Findet Schwachstellen in Startelf und B-Team — sowohl offensichtliche Lücken (Stammspieler deutlich unter dem Team-Median) als auch versteckte (ein guter Spieler wird aus seinem besten Slot gezogen oder spielt auf der falschen Seite). So verstärkst du gezielt, statt eine Position zu kaufen, die nur schwach aussieht.':
        '找出首发阵容和 B 队中的薄弱环节——既包括明显的短板（主力球员明显低于球队中位数），也包括隐藏的短板（优秀球员被调离最佳位置或踢了错误的一侧）。这样你可以有针对性地补强，而不是去买一个看起来薄弱的位置。',
    '🏆 Startelf': '🏆 首发阵容',
    '🅱️ B-Team': '🅱️ B 队',
    'Slot': '位置槽',
    'Typ': '类型',
    'Gap-Score': '短板评分',
    'Warum': '原因',
    '🟩 Auf dem Platz anzeigen': '🟩 在球场上显示',
    'Schwellen — Versteckt: %1 · Offensichtlich: %2 · Falsche-Seite-Malus: %3 (anpassbar unter Einstellungen → Schwellenwerte)':
        '阈值 — 隐性：%1 · 显性：%2 · 错误侧惩罚：%3（可在 设置 → 阈值 中调整）',
    '✅ Keine nennenswerten Lücken mit den aktuellen Schwellenwerten gefunden.':
        '✅ 按当前阈值没有发现明显的短板。',
    '%1 auffällige Position(en) gefunden — schlechteste zuerst.':
        '发现 %1 个明显薄弱的位置——最差的排在前面。',

    'Keine Daten': '无数据',
    'Noch keine historischen DWRS-Daten vorhanden.': '尚无历史 DWRS 数据。',

    // ------------------------------------------------------------- main window
    'Bereit': '就绪',
    'Neuberechnung': '重新计算',
    'DWRS neu berechnet: %1 Bewertungen, %2 geänderte Einträge gespeichert.':
        'DWRS 已重新计算：%1 项评分，保存了 %2 条变更记录。',
    '🏟 Vereins-Management': '🏟 俱乐部管理',
    '🌍 National-Management': '🌍 国家队管理',
    '🔎 Spieler suchen…': '🔎 搜索球员…',
    '🌓 Tag/Nacht wechseln': '🌓 切换日间 / 夜间模式',
    'NATIONALTEAM': '国家队',
    'VEREIN': '俱乐部',
    'ALLGEMEIN': '通用',
    '&Sprache': '语言(&S)',
    'Sprache': '语言',
    'Die Sprache wird nach einem Neustart geändert. Jetzt neu starten?':
        '语言将在重启后生效。现在重启吗？',
    'DWRS-Bewertungen werden neu berechnet…': '正在重新计算 DWRS 评分…',
    'Nationalteam': '国家队',
    'FM Dashboard': 'FM 仪表盘',
    'Aktiver Spielstand: <b>%1.db</b> · %2 Spieler': '当前存档：<b>%1.db</b> · %2 名球员',
    'Datenbank: <b>%1</b> · %2 Spieler': '数据库：<b>%1</b> · %2 名球员',

    // -------------------------------------------------------- migration wizard
    'Legacy-Datenbank importieren': '导入旧版数据库',
    'Importiert eine Datenbank der alten Streamlit-Version in das neue Format.\nDie Originaldatei wird dabei nicht verändert.':
        '将旧版 Streamlit 版本的数据库导入为新格式。\n原始文件不会被修改。',
    'Pfad zur alten .db-Datei…': '旧 .db 文件的路径…',
    'Legacy-Datenbank:': '旧版数据库：',
    'Name der neuen Datenbank (ohne .db)': '新数据库的名称（不含 .db）',
    'Ziel-Name:': '目标名称：',
    'config.ini, definitions.json, Logo und Flagge aus dem Legacy-Ordner übernehmen':
        '同时导入旧版文件夹中的 config.ini、definitions.json、队徽和国旗',
    'Import starten': '开始导入',
    'Schließen': '关闭',
    'Legacy-Datenbank wählen': '选择旧版数据库',
    'SQLite-Datenbanken (*.db);;Alle Dateien (*)': 'SQLite 数据库 (*.db);;所有文件 (*)',
    'Bitte eine vorhandene .db-Datei wählen.': '请选择一个已存在的 .db 文件。',
    'Bitte einen Ziel-Namen angeben.': '请填写目标名称。',
    'Die Datenbank \'%1\' existiert bereits. Überschreiben?':
        '数据库“%1”已存在。是否覆盖？',
    'Importiere %1 …': '正在导入 %1 …',
    'FEHLER: %1': '错误：%1',
    'Fertig: %1 Spieler, %2 Bewertungs-Einträge übernommen (%3 verwaiste übersprungen).':
        '完成：已导入 %1 名球员、%2 条评分记录（跳过 %3 条孤立记录）。',
    'Nationalkader: %1, Shortlist: %2 Spieler.': '国家队阵容：%1，候选名单：%2 名球员。',
    'Übernommen: %1': '已导入：%1',
    'WARNUNG: Die Definitionen konnten nach dem Import nicht geladen werden (%1). Die bisherigen Definitionen bleiben aktiv.':
        '警告：导入后无法加载角色定义（%1）。现有定义仍然有效。',
    'Import abgeschlossen. Die Datenbank \'%1\' kann jetzt ausgewählt werden.':
        '导入完成。现在可以选择数据库“%1”。',

    // ------------------------------------------------------- national best XI
    'Nationale Best XI': '国家队最佳阵容',
    'Die Spielzeit-Gewichtung (Agreed Playing Time) bleibt hier außen vor — sie gehört zum Verein und darf die Nationalelf-Auswahl nicht verzerren.':
        '此处不考虑出场时间权重（约定出场时间）——它属于俱乐部层面，不应影响国家队的选人。',
    'Noch keine Spieler im Nationalkader. Stelle ihn unter \'Kader-Auswahl\' zusammen.':
        '国家队阵容中还没有球员。请在“阵容选择”中组建。',
    'Keine weiteren Spieler im Kader als Tiefen-Optionen für diese Taktik geeignet.':
        '阵容中没有其他球员适合作为该战术的替补深度选项。',

    // ----------------------------------------------------------- national call-up
    '1. Aktueller Kader': '1. 当前阵容',
    'Gespeicherten Nationalkader verwenden': '使用已保存的国家队阵容',
    'Kader aus FM-HTML-Export hochladen': '从 FM HTML 导出文件上传阵容',
    'Kader-Datei wählen…': '选择阵容文件…',
    '2. Parameter': '2. 参数',
    'Kadergröße gesamt:': '阵容总人数：',
    'davon Torhüter:': '其中守门员：',
    '3. Verletzt / nicht verfügbar (für diesen Durchlauf)': '3. 受伤 / 不可用（本次征召）',
    'Pool nach Name durchsuchen…': '按姓名搜索候选池…',
    '%1 Spieler als nicht verfügbar markiert.': '已标记 %1 名球员为不可用。',
    'Nominierung berechnen': '计算征召名单',
    '✅ Einladen': '✅ 征召',
    '❌ Ausladen': '❌ 移出',
    'Empfohlenen Kader übernehmen': '采用推荐阵容',
    'Namen kopieren': '复制姓名',
    'Profil öffnen': '打开档案',

    // ------------------------------------------------- national call-up (cont.)
    '⚠️ Bitte konfiguriere zuerst dein Nationalteam vollständig unter Einstellungen → Verein (Name, Länder-Code, Altersgrenze).':
        '⚠️ 请先在 设置 → 俱乐部 中完整配置你的国家队（名称、国家代码、年龄上限）。',
    'Pool: Spieler mit Nationalität \'%1\'%2. Der Assistent stellt aus dem gesamten berechtigten Pool den stärksten Kader zusammen und vergleicht ihn mit deinem aktuellen Kader.':
        '候选池：国籍为“%1”的球员%2。助手会从全部符合资格的球员中组建最强阵容，并与你当前的阵容进行比较。',
    ' bis Alter %1': '，年龄上限 %1',
    'Hochgeladener Kader: %1 Spieler.': '已上传阵容：%1 名球员。',
    'Noch keine Kader-Datei geladen.': '尚未加载阵容文件。',
    'Gespeicherter Nationalkader: %1 Spieler.': '已保存的国家队阵容：%1 名球员。',
    'Nationalkader-Export wählen': '选择国家队阵容导出文件',
    'Nominierung': '征召',
    'Datei konnte nicht geöffnet werden: %1': '无法打开文件：%1',
    'Kader-Datei konnte nicht gelesen werden: %1': '无法读取阵容文件：%1',
    'Die Datei enthält weder eine \'UID\'- noch eine \'Name\'-Spalte.':
        '该文件既没有“UID”列也没有“Name”列。',
    'Kein Spieler aus der Datei konnte der Datenbank zugeordnet werden. Enthält der Export eine UID-Spalte?':
        '无法将文件中的任何球员与数据库匹配。该导出文件是否包含 UID 列？',
    '%1 Spieler aus der Datei als aktueller Kader übernommen.': '已采用文件中的 %1 名球员作为当前阵容。',
    '%1 nicht zugeordnet: %2': '%1 未能匹配：%2',
    'Keine Taktik ausgewählt.': '未选择战术。',
    'Bitte zuerst eine Kader-Datei hochladen oder auf den gespeicherten Kader umschalten.':
        '请先上传阵容文件，或切换到已保存的阵容。',
    'Die Torhüter-Zahl muss kleiner als die Kadergröße sein.': '守门员人数必须小于阵容总人数。',
    'Kein berechtigter, verfügbarer Spieler im Pool. Prüfe Nationalität/Altersgrenze und die Verletzten-Markierungen.':
        '候选池中没有符合资格且可用的球员。请检查国籍 / 年龄上限以及伤病标记。',
    '(nur %1 Torhüter im Pool verfügbar)': '（候选池中只有 %1 名守门员可用）',
    '<b>Empfohlener Kader:</b> %1 Spieler (%2 Torhüter%3) — Taktik %4.<br><b>%5</b> einladen, <b>%6</b> ausladen.':
        '<b>推荐阵容：</b>%1 名球员（%2 名守门员%3）— 战术 %4。<br>征召 <b>%5</b> 人，移出 <b>%6</b> 人。',
    'Kadertiefe': '阵容深度',
    '%1  ·  %2  ·  DWRS %3%': '%1  ·  %2  ·  DWRS %3%',
    'Keine — der aktuelle Kader ist bereits optimal.': '无 — 当前阵容已是最优。',
    'Retired': '已退役',
    'verletzt/gesperrt': '受伤 / 停赛',
    'nicht verfügbar/berechtigt': '不可用 / 不符合资格',
    'überzählig': '多余',
    '%1  ·  %2': '%1  ·  %2',
    'Keine — kein aktueller Spieler muss weichen.': '无 — 无需移出任何现有球员。',
    'Den empfohlenen Kader (%1 Spieler) als Nationalkader speichern? Der bisherige Nationalkader wird ersetzt.':
        '将推荐阵容（%1 名球员）保存为国家队阵容吗？原有国家队阵容将被替换。',

    // ------------------------------------------------------ national dashboard
    'Nationalkader durch Spieler dieser Datei ersetzen': '用该文件中的球员替换国家队阵容',
    'Wenn aktiviert, wird der aktuelle Nationalkader geleert und durch ALLE Spieler aus dieser HTML-Datei ersetzt — praktisch für schnelle Kader-Updates.':
        '勾选后，当前国家队阵容将被清空，并由该 HTML 文件中的全部球员替换——适合快速更新阵容。',
    'Spieler im Kader': '阵容中的球员',
    '🎯 Mögliche Nachnominierungen': '🎯 可能的补招人选',
    'Mögliche Verstärkungen aus dem berechtigten Spieler-Pool, die aktuell nicht im Kader stehen.':
        '符合资格的候选池中目前不在阵容里的潜在补强人选。',
    'Aktueller %1-Kader': '当前 %1 阵容',
    '✅ Dein Kader ist gut aufgestellt! Keine klaren Verstärkungen im berechtigten Pool gefunden.':
        '✅ 你的阵容配置良好！在符合资格的候选池中没有发现明显的补强人选。',
    '🎯 <b>Bewertung:</b> %1 %% (dein Bester: %2 %%)<br/>🎂 <b>Alter:</b> %3':
        '🎯 <b>评分：</b>%1 %% （你的最佳：%2 %%）<br/>🎂 <b>年龄：</b>%3',
    '❌ Die Datei konnte nicht importiert werden.\n\n%1':
        '❌ 无法导入该文件。\n\n%1',
    'Nationalkader': '国家队阵容',
    '🔁 Nationalkader durch %1 Spieler aus der Datei ersetzt.':
        '🔁 国家队阵容已由文件中的 %1 名球员替换。',

    // --------------------------------------------------- national squad matrix
    'Nationale Squad Matrix': '国家队阵容矩阵',
    'Extra-Details (Fuß, Größe)': '额外信息（惯用脚、身高）',
    '\'Retired\' ausblenden': '隐藏“已退役”',
    'Aktueller Kader': '当前阵容',
    'Berechtigter Pool (nicht nominiert)': '符合资格的候选池（未征召）',
    'Linker Fuß': '左脚',
    'Rechter Fuß': '右脚',
    'Größe': '身高',
    'Aktueller Kader (%1)': '当前阵容（%1）',
    'Berechtigter Pool — nicht nominiert (%1)': '符合资格的候选池 — 未征召（%1）',

    // -------------------------------------------------- national squad selection
    'Nationalkader-Auswahl': '国家队阵容选择',
    'Verfügbarer Spieler-Pool': '可用球员候选池',
    'Verfügbare Spieler nach Name durchsuchen…': '按姓名搜索可用球员…',
    'Hinzufügen →': '添加 →',
    '← Entfernen': '← 移除',
    'Nationalkader speichern': '保存国家队阵容',
    'Pool: Spieler mit Nationalität \'%1\'%2. Doppelklick oder Buttons zum Verschieben; Speichern übernimmt die Auswahl in die Datenbank.':
        '候选池：国籍为“%1”的球员%2。双击或使用按钮移动球员；保存后会将所选名单写入数据库。',
    'Aktueller Kader (%1 Spieler)%2': '当前阵容（%1 名球员）%2',
    ' — ungespeichert': ' — 未保存',
    '%1 Spieler im Nationalkader gespeichert.': '已保存 %1 名球员到国家队阵容。',

    // ------------------------------------------------------------- new role
    'Neue Rolle erstellen': '创建新角色',
    'Definiere eine neue Feldspieler-Rolle. Das Kürzel wird beim Tippen automatisch erzeugt. Nach dem Erstellen ist die Rolle überall in der App verfügbar.':
        '定义一个新的非守门员角色。缩写会在输入时自动生成。创建后该角色将在全应用可用。',
    '1. Grunddaten': '1. 基本信息',
    'Voller Rollenname:': '角色全称：',
    'z. B. \'Advanced Playmaker\'': '例如 “Advanced Playmaker”',
    'Kategorie:': '类别：',
    'Verteidigung': '防守',
    'Angriff': '进攻',
    'Aufgabe:': '职责：',
    '2. Positions-Zuordnung': '2. 位置分配',
    'Positionen ankreuzen, auf denen diese Rolle eingesetzt werden kann.':
        '勾选可以使用该角色的位置。',
    '3. Schlüssel- und bevorzugte Attribute': '3. 关键属性与偏好属性',
    '\'Schlüssel\' (S) erhält den höchsten Multiplikator, \'Bevorzugt\' (B) einen mittleren. Sind beide angekreuzt, gewinnt \'Schlüssel\'.':
        '“关键”(S) 的权重最高，“偏好”(B) 为中等权重。若两者都勾选，以“关键”为准。',
    'Technisch': '技术',
    'Mental': '精神',

    // ------------------------------------------------------------- new role (cont.)
    'Physisch': '身体',
    '<b>Erzeugtes Kürzel:</b> <code>%1</code> (dient als eindeutige ID)':
        '<b>生成的缩写：</b><code>%1</code>（作为唯一 ID 使用）',
    'Bitte gib einen Rollennamen an und wähle mindestens eine Position.':
        '请填写角色名称，并至少选择一个位置。',
    'Das Kürzel \'%1\' existiert bereits. Bitte wähle einen anderen Rollennamen oder eine andere Aufgabe.':
        '缩写“%1”已存在。请换一个角色名称或职责。',
    'Die Rolle wurde gespeichert, aber die Definitionen konnten nicht neu geladen werden: %1':
        '角色已保存，但无法重新加载角色定义：%1',
    'Rolle \'%1\' wurde erstellt und ist jetzt überall verfügbar. Weise sie unter \'Rollen zuweisen\' Spielern zu.':
        '角色“%1”已创建，现在全应用可用。请在“分配角色”中把它分配给球员。',

    // ------------------------------------------------------------ new tactic
    'Neue Taktik erstellen': '创建新战术',
    'Baue deine Formation auf dem Feld unten. Wähle für jede aktive Position eine Rolle — genau ein Torhüter und zehn Feldspieler.':
        '在下方球场上搭建你的阵型。为每个启用位置选择一个角色——正好一名守门员和十名非守门员。',
    '1. Taktik-Name': '1. 战术名称',
    'Formations-Name:': '阵型名称：',
    'z. B. \'Mein Gegenpressing\'': '例如 “我的反抢战术”',
    'Formation:': '阵型：',
    '2. Formation gestalten': '2. 设计阵型',
    'Torhüter': '守门员',
    '— Unbesetzt —': '— 空缺 —',
    '<b>Vollständiger Taktik-Name:</b> <code>%1</code>': '<b>完整战术名称：</b><code>%1</code>',
    '✅ 10 Feldspieler ausgewählt.': '✅ 已选择 10 名非守门员。',
    'Feldspieler ausgewählt: %1 / 10': '已选非守门员：%1 / 10',
    'Bitte gib sowohl einen Formations-Namen als auch eine Formation (z. B. 4-2-3-1) an.':
        '请同时填写阵型名称和阵型（例如 4-2-3-1）。',
    'Eine Taktik namens \'%1\' existiert bereits. Bitte wähle einen anderen Namen.':
        '名为“%1”的战术已存在。请换一个名称。',
    'Du musst genau 10 Feldspieler auswählen (aktuell: %1).': '你必须正好选择 10 名非守门员（当前：%1）。',
    'Bitte wähle eine Torhüter-Rolle.': '请选择一个守门员角色。',
    'Die Taktik wurde gespeichert, aber die Definitionen konnten nicht neu geladen werden: %1':
        '战术已保存，但无法重新加载定义：%1',
    'Taktik \'%1\' wurde erstellt und ist jetzt überall verfügbar.':
        '战术“%1”已创建，现在全应用可用。',

    // --------------------------------------------------- personality filter
    'Persönlichkeit:': '性格：',
    '🟢 Gut': '🟢 良好',
    '🟡 Neutral': '🟡 中性',
    '🔴 Schlecht': '🔴 差',
    'Bestimmte…': '指定…',
    'Bestimmte (%1)': '指定（%1）',
    'Diese Seite ist nicht verfügbar.': '该页面不可用。',

    // -------------------------------------------------------- player comparison
    'Pool:': '候选池：',
    'Mein Verein': '我的俱乐部',
    'Bis zu 5 Spieler ankreuzen, um sie zu vergleichen.': '最多勾选 5 名球员进行对比。',
    'Spielbereiche': '场上区域',
    'Meta-Attribut-Profil': '元属性档案',
    'Detaillierter Attribut-Vergleich': '详细属性对比',
    'Keine Spieler mit dieser Rolle im gewählten Pool gefunden.':
        '在所选候选池中没有找到该角色的球员。',
    'Bis zu 5 Spieler ankreuzen, um sie zu vergleichen (%1 verfügbar).':
        '最多勾选 5 名球员进行对比（可用 %1 名）。',
    'Höchste Prio': '最高优先级',
    'Hohe Prio': '高优先级',
    'Mittlere Prio': '中优先级',
    'Schlüssel': '关键',
    'Bevorzugt': '偏好',
    'Torwart Meta-Attribut-Profil': '守门员元属性档案',
    'Extrem wichtig': '极其重要',
    'Wichtig': '重要',
    'Gut': '良好',
    'Feldspieler Meta-Attribut-Profil': '非守门员元属性档案',
    'Bevorzugter Fuß': '惯用脚',
    'Gehalt': '周薪',

    // ---------------------------------------------------------- player profile
    '🏠 Mein Verein': '🏠 我的俱乐部',
    '🔄 Zweitteam': '🔄 二队',
    '🔍 Gescoutete': '🔍 已考察',
    '🌟 Nationalkader': '🌟 国家队阵容',
    '🌍 Alle Spieler': '🌍 全部球员',
    '🔎 Spieler suchen (Name eintippen)…': '🔎 搜索球员（输入姓名）…',
    '🔁 Diesen Spieler aus einer HTML-Datei aktualisieren': '🔁 用 HTML 文件更新该球员',
    'Lade einen FM-Export hoch, der NUR diesen Spieler enthält. Die Daten werden direkt auf dieses Profil geschrieben — auch wenn die UID in der Datei abweicht (z. B. fehlendes \'r-\'-Präfix). Zugewiesene Rollen, Primärrolle und Transfer-/Leih-Einstellungen bleiben erhalten.':
        '上传一份只包含该球员的 FM 导出文件。数据会直接写入该档案——即使文件中的 UID 不同（例如缺少 “r-” 前缀）。已分配的角色、主要角色以及转会 / 租借设置都会保留。',
    'Spieler aktualisieren': '更新球员',
    'Top-Rollen': '最佳角色（Top Roles）',
    '🌱 Talent-Projektion': '🌱 天赋预测',
    '🎯 Trainingsempfehlung': '🎯 训练建议',
    'Attribut-Übersicht': '属性总览',
    'Dieser Spieler hat noch keine bewerteten Rollen. Weise ihm auf der Seite \'Rollen zuweisen\' Rollen zu.':
        '该球员还没有已评分的角色。请在“分配角色”页面为他分配角色。',
    '<h3>Kein Spieler ausgewählt.</h3>': '<h3>未选择球员。</h3>',
    '<b>Alter:</b> %1': '<b>年龄：</b>%1',
    '<b>Verein:</b> %1': '<b>俱乐部：</b>%1',
    '<b>Position:</b> %1': '<b>位置：</b>%1',
    'Primärrolle': '主要角色',
    'Fuß': '惯用脚',
    'Status': '状态',
    'Retired (seit %1 Uploads nicht dabei)': '已退役（连续 %1 次导入未出现）',
    'Daten': '数据',
    'veraltet (vor %1 Uploads gesehen)': '已过时（上次出现于 %1 次导入前）',
    'vor %1 Uploads gesehen': '上次出现于 %1 次导入前',
    'Ja, diese Datei ist sicher ein Update für %1.': '是，该文件确实是 %1 的更新。',
    '<b style=\'font-size:14pt;\'>Talent-Score (U%1): %2</b><br/>Bester Rollen-DWRS <b>%3%</b> + Entwicklungs-Spielraum (%1−%4 Jahre) + Mentalität (Ent %5 / Arb %6) + Persönlichkeit (%7).':
        '<b style=\'font-size:14pt;\'>天赋评分（U%1）：%2</b><br/>最佳角色 DWRS <b>%3%</b> + 成长空间（%1−%4 岁）+ 心态（决心 %5 / 工作投入 %6）+ 性格（%7）。',
    'Analyse als %1': '以 %1 身份分析',
    'Stärken': '优势',
    'Keine herausragenden Stärken.': '没有突出的优势。',
    'Schwächen': '劣势',
    'Keine nennenswerten Schwächen.': '没有明显的劣势。',
    'Schlüssel-Attribute': '关键属性',
    'Bevorzugte Attribute': '偏好属性',
    'Keine Attribut-Definitionen für diese Rolle.': '该角色没有属性定义。',
    'Noch keine historischen DWRS-Daten. Importiere über die Zeit weitere Snapshots, um die Entwicklung zu sehen.':
        '尚无历史 DWRS 数据。请随时间导入更多快照以查看发展曲线。',
    '✅ %1 wurde aus der Datei aktualisiert.': '✅ %1 已从文件更新。',
    ' (Name in der Datei: \'%1\'.)': '（文件中的姓名：“%1”。）',
    'Keine trainierbare Rolle aus <i>Positionen ∩ Lieblingstaktik</i>. Lege in den Einstellungen eine Lieblings-Taktik fest.':
        '在<i>位置 ∩ 偏好战术</i>中没有可训练的角色。请在设置中指定偏好战术。',
    'Für diese Rolle gibt es aktuell keine sinnvolle Trainingsmethode (Attribute bereits hoch oder altersbedingt gesperrt).':
        '该角色目前没有有效的训练方法（属性已经很高或受年龄限制无法提升）。',
    'Trainingsmethoden in dieser Reihenfolge:': '建议按以下顺序训练：',
    'mental, lebenslang trainierbar': '精神属性，终身可训练',
    'altersbedingt nur noch begrenzt': '受年龄限制，提升有限',
    'noch voll trainierbar': '仍可全额训练',
    '⚠ Ø-Note unter 7.0 — entwickelt sich aktuell nur langsam.':
        '⚠ 平均评分低于 7.0 —— 目前成长较慢。',
    'Spieler auswählen, um den Vergleich zu sehen.': '选择一名球员即可查看对比。',

    // ------------------------------------------------------------ role analysis
    '🔍 Gescoutete Spieler': '🔍 已考察球员',
    '🔍 Gescoutete': '🔍 已考察',
    'DWRS (absolut)': 'DWRS（绝对值）',
    '%1 (%2)': '%1（%2）',
    '🏠 %1': '🏠 %1',
    '🔄 %1': '🔄 %1',
    'Zweitteam': '二队',
    'Stärken && Schwächen als %1': '作为 %1 的优势 && 劣势',
    'Keine Spieler mit dieser Rolle im gewählten Pool.': '所选候选池中没有该角色的球员。',
    'Keine herausragenden Stärken für diese Rolle.': '该角色没有突出的优势。',
    'Keine nennenswerten Schwächen für diese Rolle.': '该角色没有明显的劣势。',

    // ---------------------------------------------------------------- settings
    'DWRS-Gewichte': 'DWRS 权重',
    'Schwellenwerte': '阈值',
    'Design': '外观',
    'Datenbank': '数据库',
    'Alle Einstellungen speichern': '保存全部设置',
    'Football-Manager-Version': 'Football Manager 版本',
    '%1 (noch nicht unterstützt)': '%1（尚不支持）',
    'Version für den Import:': '导入所用版本：',
    'Bestimmt, wie die Spielerattribute aus dem HTML-Export gelesen werden. Aktuell wird Football Manager 2024 unterstützt; weitere Versionen können später ergänzt werden.':
        '决定如何从 HTML 导出中读取球员属性。目前支持 Football Manager 2024，后续可添加其他版本。',
    'Im Explorer öffnen': '在资源管理器中打开',
    'Standardordner für HTML-Import:': 'HTML 导入默认文件夹：',
    'Startordner der Dateiauswahl beim Hochladen von HTML-Exporten. Leer = automatisch: \'Sports Interactive\\Football Manager 2024\' im Dokumentenordner des aktuellen Nutzers (falls vorhanden).':
        '上传 HTML 导出时文件对话框的起始文件夹。留空 = 自动：当前用户“文档”文件夹中的 “Sports Interactive\\Football Manager 2024”（若存在）。',
    'Standardordner für HTML-Import wählen': '选择 HTML 导入默认文件夹',
    'Vereins-Zuordnung': '俱乐部关联',
    'z. B. \'FC Bayern München\' (für den Header)': '例如 “拜仁慕尼黑”（用于页头显示）',
    'z. B. \'Allianz Arena\'': '例如 “安联球场”',
    'Zweitteam:': '二队：',
    'Voller Vereinsname (Anzeige):': '俱乐部全称（用于显示）：',
    'Stadion:': '主场：',
    'Vereins-Land (3-Buchstaben-Code):': '俱乐部所在国家（3 位代码）：',
    'Logo wählen (PNG)…': '选择队徽（PNG）…',
    'Entfernen': '移除',
    'Vereinslogo:': '俱乐部队徽：',
    'Lieblings-Taktiken': '偏好战术',
    'Primäre Taktik:': '首选战术：',
    'Sekundäre Taktik:': '次选战术：',
    'z. B. Deutschland U21': '例如 “德国 U21”',
    '99 = keine Altersgrenze (A-Nationalteam); z. B. 21 für U21.':
        '99 = 无年龄限制（成年国家队）；例如 U21 填 21。',
    'Team-Name:': '球队名称：',
    'Länder-Code (3 Buchstaben):': '国家代码（3 个字母）：',
    'Altersgrenze (99 = keine):': '年龄上限（99 = 无）：',
    'Primäre National-Taktik:': '国家队首选战术：',
    'Sekundäre National-Taktik:': '国家队次选战术：',
    'Flagge wählen (PNG)…': '选择国旗（PNG）…',
    'National-Flagge:': '国旗：',
    'Diese Einstellungen gelten pro Datenbank (Spielstand). Das Vereins-Land steuert den Inland-Filter der Squad Matrix; die Lieblings-Taktiken werden auf Dashboard, Squad Matrix und Transfers vorausgewählt. Die Nationalteam-Angaben aktivieren die National-Seiten (Kader-Auswahl, National-Dashboard, …).':
        '这些设置按数据库（存档）分别保存。俱乐部所在国家决定阵容矩阵的“本国”筛选；偏好战术会在仪表盘、阵容矩阵和转会页面中预选。填写国家队信息后会启用国家队相关页面（阵容选择、国家队仪表盘等）。',
    'Vereinslogo wählen': '选择俱乐部队徽',
    'Bilder (*.png *.jpg *.jpeg *.bmp);;Alle Dateien (*)': '图片 (*.png *.jpg *.jpeg *.bmp);;所有文件 (*)',
    'Vereinslogo': '俱乐部队徽',
    'Die Datei konnte nicht als Bild geladen werden.': '无法将该文件作为图片加载。',
    'Das Logo konnte nicht gespeichert werden.': '无法保存队徽。',
    '(kein Logo)': '（无队徽）',
    'National-Flagge wählen': '选择国旗',
    'National-Flagge': '国旗',
    'Die Flagge konnte nicht gespeichert werden.': '无法保存国旗。',
    '(keine Flagge)': '（无国旗）',
    'Feldspieler-Kategorien': '非守门员属性类别',
    'Torwart-Kategorien': '守门员属性类别',
    'Rollen-Multiplikatoren': '角色倍率',
    'Schlüssel-Attribute:': '关键属性：',
    'Bevorzugte Attribute:': '偏好属性：',
    'Spielzeit-Gewichte (Agreed Playing Time)': '出场时间权重（约定出场时间）',
    'Jugend-Altersgrenzen': '青年球员年龄上限',
    'Feldspieler bis Alter:': '非守门员年龄上限：',
    'Torhüter bis Alter:': '守门员年龄上限：',
    'Kader-Management': '阵容管理',
    'Bonus natürliche Position:': '擅长位置加成：',
    'Max. Rollen pro Depth-Spieler:': '每名替补球员最多角色数：',
    'Min. Talent-Score für Leihe:': '外租所需最低天赋评分：',
    'Mindestalter für Leihe:': '外租最低年龄：',
    'Jugendelf-Leihe erst über Alter:': '青年队球员外租起始年龄：',
    'Gap-Analyse': '短板分析',
    'Displacement-Schwelle:': '错位阈值：',
    'Dropoff-Schwelle:': '落差阈值：',
    'Falsche-Seite-Malus:': '错误侧惩罚：',
    'Datenfrische / Retired': '数据新鲜度 / 退役',
    'Retired ab Alter (X):': '退役起始年龄（X）：',
    'Veraltet/Retired nach Uploads ohne Update (Y):': '连续 Y 次导入未更新视为过时 / 退役：',
    'Jeder Import zählt hoch. Ein Spieler, der seit Y Uploads nicht mehr dabei war, gilt als veraltet. Ist er zusätzlich mindestens X Jahre alt und nicht in deinem Verein, wird er automatisch als Retired angezeigt.':
        '每次导入都会累加计数。连续 Y 次导入中未出现的球员会被视为数据过时。若他同时年满 X 岁且不在你的俱乐部，则会自动显示为“已退役”。',
    'Trainings-Altersfenster': '训练年龄区间',
    'stark bis': '高效训练至',
    'gesperrt ab': '停止提升于',
    'Explosiv (Tempo, Antritt, Beweglichkeit):': '爆发类（速度、加速、灵活）：',
    'Kraft (Kraft, Ausdauer, Sprungkraft, Balance):': '力量类（强壮、耐力、弹跳、平衡）：',
    'Technik:': '技术：',
    'Steuert die Trainingsempfehlung: bis \'stark bis\' voll trainierbar, danach linear abnehmend bis \'gesperrt ab\'. Mentale Attribute gelten immer als trainierbar, Charakter-Attribute (Entschlossenheit, Arbeitsrate) nie (nur über Mentoring).':
        '用于生成训练建议：在“高效训练至”之前可全额训练，之后线性递减直至“停止提升于”。精神属性始终视为可训练；性格属性（决心、工作投入）永远不可训练（只能通过导师制提升）。',

    // -------------------------------------------------------- settings (theme/DB)
    'Benutzerdefiniert': '自定义',
    'Nacht (dunkel)': '夜间（深色）',
    'Tag (hell)': '日间（浅色）',
    'Vereins-/Farbvorlage:': '俱乐部 / 配色模板：',
    'Aktiver Modus:': '当前模式：',
    'Eine Vorlage setzt eine ruhige Anthrazit-Basis und nur die Vereinsfarben als Akzent (Kopfzeile, Buttons, Interaktion). Farben unten lassen sich danach frei anpassen — das schaltet auf \'Benutzerdefiniert\'.':
        '模板会设定沉稳的深灰底色，只把俱乐部颜色用作点缀（页头、按钮、交互元素）。之后可以自由调整下方颜色——此时会自动切换到“自定义”。',
    'Hintergrund': '背景',
    'Panel / Karten': '面板 / 卡片',
    'Sidebar': '侧边栏',
    'Kopfzeile': '页头',
    'Primär / Buttons': '主色 / 按钮',
    'Interaktion (Tabs, Slider)': '交互元素（标签页、滑块）',
    'Text': '文字',
    'Nacht-Farben': '夜间配色',
    'Tag-Farben': '日间配色',
    'Farbe wählen': '选择颜色',
    'Farbschema': '配色方案',
    'Aktive Datenbank': '当前数据库',
    'Wechseln': '切换',
    'Neue Datenbank anlegen…': '新建数据库…',
    'Legacy-Datenbank importieren…': '导入旧版数据库…',
    'Neue Datenbank': '新建数据库',
    'Name (ohne .db):': '名称（不含 .db）：',
    'Import': '导入',
    'Importierte Datenbank \'%1\' jetzt aktivieren?': '现在启用已导入的数据库“%1”吗？',
    'Datenordner: %1\n(Änderbar über bootstrap.ini; Verschiebe-Assistent folgt in einem späteren Meilenstein.)':
        '数据文件夹：%1\n（可通过 bootstrap.ini 修改；移动向导将在后续版本中提供。）',
    '⚠ %1: Kontrast Text/Hintergrund nur %2:1 (WCAG empfiehlt ≥ 4,5:1)':
        '⚠ %1：文字与背景的对比度仅为 %2:1（WCAG 建议 ≥ 4.5:1）',
    'Nacht': '夜间',
    'Tag': '日间',
    '✓ Kontrastwerte in Ordnung': '✓ 对比度正常',
    'Einstellungen gespeichert.': '设置已保存。',

    // ------------------------------------------------------------- squad matrix
    'Extra-Details': '额外信息',
    'Zweitteam separat anzeigen': '单独显示二队',
    '🌱 Talent-Filter': '🌱 天赋筛选',
    'Nationalität:': '国籍：',
    'Inland': '本国',
    'Ausland': '外籍',
    'Beliebig': '不限',
    'Min. Ent + Arb:': '最低 决心 + 工作投入：',
    'Nur gute Persönlichkeiten': '仅良好性格',
    'Talent-Score = bester DWRS der angezeigten Rollen + 2 je Jahr unter der Altersgrenze + (Ent + Arb − 20) / 4 + 3 (gute) / − 5 (schlechte Persönlichkeit).':
        '天赋评分 = 所显示角色中的最佳 DWRS + 每低于年龄上限 1 岁加 2 分 + （决心 + 工作投入 − 20）/ 4 + 3（性格良好）/ − 5（性格差）。',
    'Gescoutete Spieler': '已考察球员',
    'Kein Limit': '无限制',
    'Filter/Sortierung:': '筛选 / 排序：',
    'Nur Free Agents': '仅自由球员',
    'Nur ablösefreie Spieler: Marktwert explizit 0 oder kein Verein gesetzt (unabhängig davon, wie der Verein benannt ist). Marktwert-Limit wird dabei ignoriert; nach Rolle/Talent sortierbar.':
        '仅显示自由球员：身价明确为 0，或未设置俱乐部（与俱乐部名称的写法无关）。此时忽略身价上限；可按角色 / 天赋排序。',
    'Nation:': '国家：',
    'Nach Nationalität einschränken (unabhängig vom Talent-Filter): eigenes Land, Ausländer oder eine bestimmte Nation — hilfreich für Registrierungsregeln.':
        '按国籍筛选（与天赋筛选无关）：本国、外籍或指定国家——对注册规则很有帮助。',
    'DWRS:': 'DWRS：',
    'Alter:': '年龄：',
    'Max. Wert:': '最高身价：',
    'CSV exportieren': '导出 CSV',
    '★': '★',
    'Ausländer': '外籍球员',
    'Inland (Land fehlt in Einstellungen)': '本国（设置中未填写国家）',
    'Inland (%1)': '本国（%1）',
    'Spieler von %1 & Zweitteam (%2)': '%1 及二队的球员（%2）',
    'Spieler von %1 (%2)': '%1 的球员（%2）',
    'Spieler von %1 (Zweitteam, %2)': '%1 的球员（二队，%2）',
    'Shortlist': '候选名单',
    'Free Agents (%1)': '自由球员（%1）',
    'Gescoutete Spieler (%1)': '已考察球员（%1）',
    'CSV-Dateien (*.csv)': 'CSV 文件 (*.csv)',

    // ---------------------------------------------------------- tactic explorer
    'Bewertet deinen Kader gegen JEDE Taktik, um die beste Passung zu finden — besonders nützlich bei der Übernahme eines unbekannten Teams. Sortiert wird zuerst nach Abdeckung (wie viele Positionen du besetzen kannst), dann nach Stärke (Median-DWRS der besten Elf, nur über besetzte Slots gemessen).':
        '把你的阵容与每一种战术进行匹配评分，找出最合适的一种——接手陌生球队时尤其有用。排序先按覆盖度（你能填补多少个位置），再按强度（最佳十一人的 DWRS 中位数，仅统计已填补的位置）。',
    'Taktik': '战术',
    'XI': '十一人',
    'Leer': '空缺',
    'Dünn': '薄弱',
    'Median': '中位数',
    'Ø': '平均',
    'GK/DEF/DM/MID/AM/ST = Median-DWRS je Mannschaftsteil. Leer = Slots, die die beste Elf nicht besetzen konnte · Dünn = nur ein geeigneter Spieler (kein Backup).':
        'GK/DEF/DM/MID/AM/ST = 各条线的 DWRS 中位数。空缺 = 最佳十一人无法填补的位置槽 · 薄弱 = 只有一名合适球员（没有替补）。',
    'Taktik im Detail': '战术详情',
    'Geeignete Spieler': '合适的球员',
    '%1-Kader': '%1 阵容',
    'Pool: %1 Spieler (%2).': '候选池：%1 名球员（%2）。',
    '🏆 <b>Beste Passung: %1</b> — besetzt %2/%3 Positionen, Median-DWRS %4.':
        '🏆 <b>最佳匹配：%1</b> — 填补 %2/%3 个位置，DWRS 中位数 %4。',
    '<b>Besetzte Positionen:</b> %1/%2 &nbsp;·&nbsp; <b>Median-DWRS:</b> %3 &nbsp;·&nbsp; <b>Ø Optionen pro Slot:</b> %4':
        '<b>已填补位置：</b>%1/%2 &nbsp;·&nbsp; <b>DWRS 中位数：</b>%3 &nbsp;·&nbsp; <b>每个位置平均人选：</b>%4',
    '⛔ <b>Gar kein geeigneter Spieler</b> für: %1 — für diese Formation fehlen dir Spielertypen.':
        '⛔ <b>完全没有合适的球员</b>：%1 — 你的阵容缺少该阵型需要的球员类型。',
    '⚠️ <b>In der besten Elf leer geblieben</b> (Spieler existieren, werden aber woanders gebraucht): %1':
        '⚠️ <b>在最佳十一人中仍然空缺</b>（有球员，但需要用在别处）：%1',
    '<b>Nur eine Option (kein Backup):</b> %1': '<b>只有一个人选（无替补）：</b>%1',

    // ------------------------------------------------------------ training plan
    '🔄 Aktualisieren': '🔄 刷新',
    'Kader, Rollen und Empfehlungen neu berechnen (z. B. nach Änderungen an den Rollen).':
        '重新计算阵容、角色和建议（例如在修改角色之后）。',
    'Erste Mannschaft': '一线队',
    'Trainingsrolle': '训练角色',
    'Trainingsmethoden (in Reihenfolge)': '训练项目（按顺序）',
    'Rolle wählbar aus <i>Positionen ∩ Taktik</i> (wird gespeichert). Reihenfolge der Methoden = größter DWRS-Gewinn zuerst; Reha-Methoden werden nicht vorgeschlagen. Spaltenkopf klicken sortiert.':
        '角色可从<i>位置 ∩ 战术</i>中选择（会被保存）。训练项目按 DWRS 收益从高到低排序；不会推荐康复类项目。点击列标题可排序。',
    'nichts sinnvoll trainierbar': '没有值得训练的项目',
    '⚠️ Kein Verein gesetzt. Wähle unter Einstellungen → Verein \'Mein Verein\', damit dein Kader angezeigt wird.':
        '⚠️ 未设置俱乐部。请在 设置 → 俱乐部 中选择“我的俱乐部”，以显示你的阵容。',
    'keine Rolle in dieser Taktik': '该战术中没有此角色',

    // ---------------------------------------------------------------- transfers
    'Transfer- && Leih-Management': '转会 && 租借管理',
    'Verwaltet die überzähligen Spieler für die gewählte Taktik — Spieler, die es weder in die Erste Elf noch in B-, Zweit- oder Jugendteam geschafft haben. Häkchen setzen, optional neuen Verein eintragen, dann speichern.':
        '管理所选战术下的多余球员——既没进首发十一人，也没进 B 队、二队或青年队的球员。勾选相应选项，可选填写新俱乐部，然后保存。',
    'Zum Verleihen (vielversprechende Talente)': '可外租（有潜力的新星）',
    'Zum Verkauf / zur Freigabe': '可出售 / 解约',
    'Bester DWRS (Rolle)': '最佳 DWRS（角色）',
    'Neuer Verein': '新俱乐部',
    'Alle Änderungen dieser Liste speichern': '保存此列表中的所有修改',
    '%1 Spieler-Datensätze gespeichert.': '已保存 %1 条球员数据。',
};
